//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project1
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalCard
    {
        public int id { get; set; }
        public Nullable<int> idPatient { get; set; }
        public Nullable<int> idDoctor { get; set; }
        public System.DateTime DateOfVisit { get; set; }
        public string ReaseachProtacol { get; set; }
        public string Conclusion { get; set; }
        public Nullable<int> idDiagnosis { get; set; }
        public string Recomendatein { get; set; }
    
        public virtual Diagnosis Diagnosis { get; set; }
        public virtual Doctor Doctor { get; set; }
        public virtual Patient Patient { get; set; }
        public override string ToString()
        {
            return $"{id,4} {idPatient,4} {idDoctor,4} {DateOfVisit,22} {ReaseachProtacol,30} {Conclusion,50} {idDiagnosis,4} {Recomendatein}";
        }
    }
}
